package com.ephemeral.chat.plugins.game.whospy

/**
 * 谁是卧底内置词库——100 对相近词语。
 * 每对包含平民词和卧底词，游戏中随机选择一对并随机分配。
 */
object WordPairs {

    data class WordPair(val civilianWord: String, val spyWord: String)

    val pairs: List<WordPair> = listOf(
        WordPair("泡面", "方便面"),
        WordPair("草莓", "蓝莓"),
        WordPair("汉堡", "三明治"),
        WordPair("咖啡", "可可"),
        WordPair("奶茶", "奶绿"),
        WordPair("饺子", "馄饨"),
        WordPair("可乐", "雪碧"),
        WordPair("冰淇淋", "雪糕"),
        WordPair("薯条", "薯片"),
        WordPair("蛋糕", "面包"),
        WordPair("苹果", "梨子"),
        WordPair("香蕉", "芭蕉"),
        WordPair("葡萄", "提子"),
        WordPair("橙子", "橘子"),
        WordPair("西瓜", "哈密瓜"),
        WordPair("芒果", "榴莲"),
        WordPair("樱桃", "车厘子"),
        WordPair("猕猴桃", "火龙果"),
        WordPair("柠檬", "青柠"),
        WordPair("菠萝", "凤梨"),
        WordPair("手机", "平板"),
        WordPair("电脑", "笔记本"),
        WordPair("键盘", "鼠标"),
        WordPair("耳机", "音箱"),
        WordPair("相机", "摄像机"),
        WordPair("电视", "投影仪"),
        WordPair("空调", "电扇"),
        WordPair("冰箱", "冰柜"),
        WordPair("微波炉", "烤箱"),
        WordPair("电饭煲", "压力锅"),
        WordPair("牙刷", "牙膏"),
        WordPair("毛巾", "浴巾"),
        WordPair("枕头", "抱枕"),
        WordPair("被子", "毛毯"),
        WordPair("拖鞋", "凉鞋"),
        WordPair("雨伞", "遮阳伞"),
        WordPair("书包", "手提包"),
        WordPair("钱包", "卡包"),
        WordPair("眼镜", "墨镜"),
        WordPair("手表", "手环"),
        WordPair("戒指", "耳环"),
        WordPair("项链", "手链"),
        WordPair("口红", "唇膏"),
        WordPair("香水", "花露水"),
        WordPair("洗发水", "沐浴露"),
        WordPair("面霜", "乳液"),
        WordPair("防晒霜", "隔离霜"),
        WordPair("医生", "护士"),
        WordPair("老师", "教授"),
        WordPair("学生", "学徒"),
        WordPair("警察", "保安"),
        WordPair("消防员", "急救员"),
        WordPair("司机", "乘务员"),
        WordPair("厨师", "帮厨"),
        WordPair("画家", "书法家"),
        WordPair("歌手", "作曲家"),
        WordPair("演员", "导演"),
        WordPair("舞者", "体操运动员"),
        WordPair("篮球", "排球"),
        WordPair("足球", "橄榄球"),
        WordPair("网球", "羽毛球"),
        WordPair("乒乓球", "台球"),
        WordPair("游泳", "跳水"),
        WordPair("滑雪", "滑冰"),
        WordPair("跑步", "竞走"),
        WordPair("骑车", "滑板"),
        WordPair("爬山", "攀岩"),
        WordPair("钓鱼", "捕鱼"),
        WordPair("春节", "元旦"),
        WordPair("中秋", "端午"),
        WordPair("清明", "重阳"),
        WordPair("国庆", "劳动节"),
        WordPair("圣诞", "复活节"),
        WordPair("生日", "满月"),
        WordPair("婚礼", "订婚"),
        WordPair("毕业", "结业"),
        WordPair("地铁", "轻轨"),
        WordPair("公交", "客车"),
        WordPair("高铁", "动车"),
        WordPair("飞机", "直升机"),
        WordPair("轮船", "游艇"),
        WordPair("自行车", "电动车"),
        WordPair("红玫瑰", "白玫瑰"),
        WordPair("百合", "郁金香"),
        WordPair("向日葵", "菊花"),
        WordPair("樱花", "桃花"),
        WordPair("荷花", "睡莲"),
        WordPair("仙人掌", "芦荟"),
        WordPair("图书馆", "书店"),
        WordPair("电影院", "剧院"),
        WordPair("博物馆", "美术馆"),
        WordPair("健身房", "体育馆"),
        WordPair("超市", "便利店"),
        WordPair("酒店", "民宿"),
        WordPair("医院", "诊所"),
        WordPair("学校", "培训机构"),
        WordPair("银行", "信用社"),
        WordPair("公园", "广场"),
        WordPair("游乐园", "水上乐园"),
        WordPair("餐厅", "食堂"),
        WordPair("咖啡馆", "茶馆"),
        WordPair("酒吧", "夜店"),
    )
}
